spring:
  activemq:
    broker-url: tcp://localhost:61616  #activemq的连接url,还可以指定连接的用户名和密码
  devtools:
    restart:
      enabled: true #开启热部署
#datasource数据库连接信息
datasource: 
#第一个数据库
    base: 
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://192.168.0.99:3306/basedata?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: 123456
      connectionTimeout: 3000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 10
      maximumPoolSize: 50    
#第二个数据库
    main: 
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://192.168.0.99:3306/db_eshop?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: 123456
      connectionTimeout: 3000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 10
      maximumPoolSize: 50
project:
  name:aaasss
